consumers:
  - name: consumer_1
    topic: topic_1
    subscription_name: subscription_1
    subscription_type: exclusive

  - name: consumer_2
    topic: topic_2
    subscription_name: subscription_2
    subscription_type: shared

  - name: consumer_3
    topic: topic_3
    subscription_name: subscription_3
    subscription_type: failover
