producers:
  - name: producer_1
    topic: /default/topic_1
    schema: json
    json_schema: '{"type": "object", "properties": {"field1": {"type": "string"}, "field2": {"type": "integer"}}}'

  - name: producer_2
    topic: /default/topic_2
    schema: string

  - name: producer_3
    topic: /default/topic_3
    schema: number
